import {balancePlan,balanceProgress,startBalance,continueTournament,MIN_PLAYERS,MAX_PLAYERS,clone,addPlayers,createTournament,levels,progress,recordScore,undoLast,standings,finish,league,completed,h2h,awards,removeTournament,percent,report,validateDB,transition} from './domain.js';
import {openStore,backupBeforeReplace,readPreviousBackup} from './storage.js';
import {readCloud,writeCloud,loginOrganizer,logoutOrganizer,isOrganizer} from './cloud.js';

let db,busy=false,locked=false,selected=new Set(),draftTitle='',message='',toastTimer;
let legacy=null,refreshing=false,stale=false,roleChosen=false;
const root=document.querySelector('#app'),dialog=document.querySelector('#modal');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shortDate=s=>new Date(s).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});
const nm=(t,id)=>esc(t.names[id]);
const active=()=>db.tournaments.find(t=>t.status==='active');
const btn=(label,action,extra='',kind='')=>`<button type="button" class="btn ${kind}" data-action="${action}" ${extra}>${label}</button>`;
function toast(s){const el=document.querySelector('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4200);}
function navigate(hash){if(location.hash===hash)render();else location.hash=hash;}
function ask(title,body,ok='Подтвердить',danger=false,input=null){
  return new Promise(resolve=>{dialog.returnValue='no';dialog.innerHTML=`<form id="modal-form"><h2>${esc(title)}</h2><div class="small">${body}</div>${input!==null?`<label class="gap">Имя игрока<input name="value" value="${esc(input)}" required maxlength="40" autocomplete="off"></label>`:''}<div class="actions"><button class="btn" type="button" id="modal-cancel">Отмена</button><button class="btn ${danger?'danger':'primary'}" type="submit">${esc(ok)}</button></div></form>`;
  dialog.onclose=()=>{dialog.onclose=null;resolve(dialog.returnValue==='yes'?(input===null?true:dialog.querySelector('input').value.trim()):null);};
  dialog.querySelector('#modal-cancel').onclick=()=>dialog.close('no');dialog.querySelector('form').onsubmit=e=>{e.preventDefault();dialog.close('yes');};dialog.showModal();});
}
async function mutate(fn){if(!roleChosen||!isOrganizer())throw Error('Для изменения данных войдите как организатор.');if(stale)throw Error('Данные изменились. Нажмите «Обновить» и проверьте текущий матч.');if(busy||locked)throw Error('Дождитесь сохранения.');busy=true;document.querySelector('#save-status').textContent='Сохраняем в облако…';try{const next=clone(db);const result=fn(next);next.revision=db.revision+1;await writeCloud(next);db=next;render();document.querySelector('#save-status').textContent='Сохранено в общей базе';return result;}catch(err){if(err.conflict)stale=true;throw err;}finally{busy=false;}}
function error(e){toast(e.message||'Не удалось выполнить действие.');document.querySelector('#save-status').textContent='Проверьте сохранение';}
function namesForm(){return `<form data-form="add-player" class="gap"><div class="field-row"><label>Добавить игрока<input name="names" placeholder="Игорь, Саша, Яша…" maxlength="400" required autocomplete="off"></label><button class="btn">Добавить</button></div><p class="muted small gap">Несколько имён можно разделить запятой. Профили сохранятся для следующих турниров.</p></form>`;}
function rules(){return `<details><summary>Как играем и считаем очки</summary><ul class="rule-list"><li>Одна партия до 11, при 10:10 — до разницы в 2 очка.</li><li>Победа на старте: 2 очка. Gold: 3, Silver: 2, Bronze: 1. Поражение: 0.</li><li>Победа поднимает на один уровень, поражение опускает. В Gold победитель остаётся, в Bronze проигравший остаётся.</li><li>Сначала играет участник с наименьшим числом матчей; при равенстве — тот, кто дольше ждал.</li><li>Соперник: меньше матчей, ближе уровень, меньше повторов, дольше ожидание. Кнопка «Выровнять» доводит всех до ближайшего достижимого числа игр. Очки — по уровню победителя до игры.</li><li>При нечётном числе игроков последний в случайной жеребьёвке получает проход в Gold после стартовых матчей, без победы и очков.</li><li>Места: очки турнира → процент побед → средняя разница очков за матч → стартовая жеребьёвка. Конечный уровень не решает место.</li><li>Сезонные очки за места 1–8: 15 / 10 / 7 / 5 / 4 / 3 / 2 / 1. С 9-го места — 0.</li><li>Число матчей может отличаться. Завершение по кнопке, после стартовых матчей. Несыгранная следующая пара не учитывается.</li></ul></details>`;}
function tournamentPage(){const t=active();if(t)return livePage(t);const ps=db.players.filter(p=>!p.archived);selected=new Set([...selected].filter(id=>ps.some(p=>p.id===id)));return `<div class="desktop-columns"><section class="panel"><span class="eyebrow">НОВЫЙ ТУРНИР</span><h1>Кто играет сегодня?</h1><p class="muted">Один стол. Все в игре до конца.</p>${namesForm()}<form data-form="start"><div class="players-grid">${ps.map(p=>`<label class="pick"><input type="checkbox" name="participant" value="${esc(p.id)}" ${selected.has(p.id)?'checked':''}><span>${esc(p.name)}</span></label>`).join('')}</div>${!ps.length?'<p class="muted small">Начните с имён вашей компании.</p>':''}<label>Название турнира<input name="title" maxlength="80" value="${esc(draftTitle)}" placeholder="Вечерняя лига · ${shortDate(new Date())}"></label><div class="row gap"><span class="small muted" id="selected-count">Выбрано: ${selected.size} из ${MIN_PLAYERS}–${MAX_PLAYERS}</span><span class="badge">Случайный старт</span></div><button id="start-button" class="btn primary wide gap" ${selected.size<MIN_PLAYERS||selected.size>MAX_PLAYERS?'disabled':''}>Начать турнир</button></form></section><section class="panel"><span class="eyebrow">ПРАВИЛА TT LEAGUE</span><h2 class="gap">Побеждай. Поднимайся.</h2><div class="stat-grid"><div class="stat"><strong>3</strong><span>за Gold</span></div><div class="stat"><strong>2</strong><span>за Silver</span></div><div class="stat"><strong>1</strong><span>за Bronze</span></div></div><p class="small muted">Программа назначает матчи и обновляет группы после каждого счёта. Накопленные очки определяют итоговые места.</p>${rules()}<div class="notice gap">Профили и результаты общие для всех устройств. Для сохранения нужна связь с интернетом.</div></section></div>`;}
function groups(t){const lv=levels(t),opening=t.matches.length<Math.floor(t.ids.length/2);let names=opening?['Common','Gold','Silver']:['Gold','Silver','Bronze'];names=names.filter(l=>!opening||t.ids.some(id=>lv[id]===l));const current=t.current;return `<div class="groups ${names.length===1?'single':''}">${names.map(l=>{const ids=t.draw.filter(id=>lv[id]===l);return `<section class="group ${l==='Common'?'common':l.toLowerCase()}" aria-label="${l==='Common'?'Общая группа':l}"><h3 class="group-title">${l==='Common'?'Общая группа':l}<span>${ids.length}</span></h3>${ids.map(id=>`<div class="group-member ${current&&(current.a===id||current.b===id)?'playing':''}">${nm(t,id)}${current&&(current.a===id||current.b===id)?'<small>Играет сейчас</small>':''}</div>`).join('')||'<p class="group-empty">Пока никого</p>'}</section>`}).join('')}</div>`;}
function standingsTable(t,final=false){const rows=standings(t);return `<div class="table-scroll"><table><thead><tr><th>#</th><th>Игрок</th><th>И / В</th><th>Очки${final?' / сезон':''}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.place}</td><td><b>${nm(t,r.id)}</b><br><span class="muted small">${percent(r.wins,r.games)} · ${r.level==='Common'?'Старт':r.level}</span></td><td class="number">${r.games} / ${r.wins}</td><td class="number"><b>${r.points}</b>${final?` <span class="muted">/ +${r.seasonPoints}</span>`:''}</td></tr>`).join('')}</tbody></table></div>`;}
function matchList(t){return [...t.matches].reverse().map((m,i)=>`<div class="list-item"><div class="row"><div class="small"><span class="muted">${t.matches.length-i}.</span> ${nm(t,m.a)} — ${nm(t,m.b)}<br><span class="muted">${m.levelA==='Common'?'Старт':m.levelA}${m.cross?` / ${m.levelB}`:''} · ${nm(t,m.winner)} +${m.points}</span></div><span class="history-score number">${m.scoreA}:${m.scoreB}</span></div></div>`).join('')||'<p class="muted small gap">Счёт первого матча появится здесь.</p>';}
function livePage(t){const p=t.current,lv=levels(t),last=t.matches.at(-1),opening=t.matches.length<Math.floor(t.ids.length/2),balance=balanceProgress(t);return `<div class="row wrap title-row"><div><span class="eyebrow">${opening?'СТАРТОВЫЕ МАТЧИ':'ТУРНИР ИДЁТ'}</span><h2>${esc(t.title)}</h2></div><span class="elapsed muted" id="elapsed" data-time="${t.startedAt}"></span></div><div class="desktop-columns"><div>${balance?`<p class="notice">Выравнивание до ${balance.target} матчей каждому · осталось встреч: ${balance.remaining}</p>`:''}${p?`<section class="match-card"><div class="row"><span class="eyebrow">СЕЙЧАС ИГРАЮТ</span><span class="small">Матч ${t.matches.length+1}</span></div><form data-form="score" data-tournament="${t.id}" data-match-count="${t.matches.length}" data-revision="${t.revision}"><div class="scoreline"><label>${nm(t,p.a)}<input aria-label="Счёт ${nm(t,p.a)}" type="number" name="a" min="0" max="999" step="1" inputmode="numeric" autocomplete="off" required></label><span class="versus">VS</span><label>${nm(t,p.b)}<input aria-label="Счёт ${nm(t,p.b)}" type="number" name="b" min="0" max="999" step="1" inputmode="numeric" autocomplete="off" required></label></div><button class="btn lime wide">Сохранить счёт →</button><p class="inline-error" role="alert" id="score-error"></p></form><p class="small muted gap">${esc(p.reason)}${p.cross?` · ${lv[p.a]} / ${lv[p.b]}`:''}</p></section>`:`<section class="panel"><h2>Игры выровнены</h2><p>У всех по ${balance?.target} матчей.</p>${btn('Продолжить турнир','continue',`data-id="${t.id}"`,'primary')}</section>`}${message?`<p class="notice" role="status">${esc(message)}</p>`:last?`<p class="notice">Последний матч: ${nm(t,last.winner)} +${last.points} очк.</p>`:''}<div class="row wrap gap">${btn('Выровнять','balance',`data-id="${t.id}" ${opening||balance?'disabled':''}`)}${btn('Завершить турнир','finish',`data-id="${t.id}"`,'primary')}${btn('Отменить последний счёт','undo',`data-id="${t.id}" ${!t.matches.length?'disabled':''}`,'text')}</div></div><div><div class="row gap"><h2>Группы сейчас</h2><span class="muted small">${t.ids.length} игроков</span></div>${groups(t)}${t.ids.length%2?`<p class="small muted">${opening?'После стартовых матчей':'Стартовый проход'}: ${nm(t,t.draw.at(-1))} → Gold, без очков.</p>`:''}<details><summary>Текущая таблица · ${t.matches.length} матчей</summary>${standingsTable(t)}</details><details><summary>История матчей</summary>${matchList(t)}</details>${rules()}<p class="footer-note">Результаты сохраняются в общей базе после каждого матча.</p></div></div>`;}
function playersPage(){return `<section class="panel"><span class="eyebrow">НАША КОМПАНИЯ</span><h1>Игроки</h1><p class="muted small">Профили остаются с вами от турнира к турниру.</p>${namesForm()}<div class="gap">${db.players.map(p=>`<div class="list-item row"><a class="person list-link" href="#player/${p.id}"><span class="avatar">${esc(p.name[0].toUpperCase())}</span><span><b>${esc(p.name)}</b>${p.archived?'<small class="muted"> · В архиве</small>':''}</span></a><div>${btn('Имя','rename',`data-id="${p.id}"`,'text')}${btn(p.archived?'Вернуть':'В архив','archive',`data-id="${p.id}"`,'text')}</div></div>`).join('')}</div></section>`;}
function historyPage(){const ts=[...db.tournaments].reverse();return `<section class="panel"><span class="eyebrow">СОХРАНЁННЫЕ ВСТРЕЧИ</span><h1>История турниров</h1><p class="muted small">Можно удалить тестовый турнир. Его очки и матчи исчезнут из статистики, профили останутся.</p><div class="gap">${ts.map(t=>`<div class="list-item"><div class="row"><a class="list-link" href="${t.status==='active'?'#tournament':`#results/${t.id}`}"><h3>${esc(t.title)}</h3><span class="small muted">${shortDate(t.startedAt)} · ${t.ids.length} игроков · ${t.matches.length} матчей</span><br><span class="badge">${t.status==='active'?'Сейчас идёт':`Чемпион: ${nm(t,standings(t)[0].id)}`}</span></a>${btn('Удалить','delete',`data-id="${t.id}"`,'danger')}</div></div>`).join('')||'<div class="empty"><span class="empty-symbol">▤</span><h2>Здесь будет история</h2><p class="muted small gap">Завершённые турниры сохраняются автоматически.</p><a class="btn primary list-link gap" href="#tournament">К турниру</a></div>'}</div></section>${backupPanel()}`;}
function backupPanel(){return `<section class="panel"><h2>Ваша лига — с вами</h2><p class="muted small gap">Копия содержит профили, турниры и все результаты. На другом телефоне загрузите этот файл. Результаты хранятся в общей базе. Импорт заменяет данные лиги для всех участников.</p><div class="row wrap gap">${btn('Скачать копию JSON','backup')}${btn('Восстановить из файла','import')}${legacy?.tournaments.length||legacy?.players.length?btn('Перенести старые данные этого браузера','migrate-local'):''}</div><input type="file" id="import-file" accept=".json,application/json" hidden><details><summary>Резерв перед последним импортом</summary><p>Перед заменой данных приложение сохраняет предыдущую базу на этом устройстве.</p>${btn('Скачать предыдущую базу','previous-backup','class="gap"')}</details></section>`;}
function leaguePage(){const rows=league(db).filter(p=>p.tournaments);return `<section class="panel"><span class="eyebrow">ОСНОВНОЙ СЕЗОН</span><h1>Рейтинг лиги</h1><p class="muted small">Очки за места в завершённых турнирах. Текущий турнир пока не учитывается.</p>${rows.length?`<div class="table-scroll gap"><table><thead><tr><th>#</th><th>Игрок</th><th>Титулы</th><th>Очки</th></tr></thead><tbody>${rows.map((p,i)=>`<tr><td>${i+1}</td><td><a href="#player/${p.id}"><b>${esc(p.name)}</b></a><br><span class="small muted">${p.wins}–${p.losses} · ${percent(p.wins,p.games)}</span></td><td>${p.titles}</td><td><b>${p.points}</b></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><span class="empty-symbol">▥</span><p>Завершите первый турнир — появится рейтинг.</p></div>'}${rules()}</section>`;}
function playerPage(id){const p=db.players.find(x=>x.id===id);if(!p)return '<section class="panel">Игрок не найден.</section>';const row=league(db).find(x=>x.id===id),ts=completed(db),tournaments=ts.filter(t=>t.ids.includes(id)),ach=tournaments.flatMap(t=>awards(t,ts.slice(0,ts.findIndex(x=>x.id===t.id))).filter(a=>a.id===id).map(a=>({...a,date:t.startedAt,titleOfTournament:t.title})));return `<section class="panel"><a class="muted small" href="#players">← Все игроки</a><h1 class="gap">${esc(p.name)}</h1><div class="stat-grid"><div class="stat"><strong>${row.points}</strong><span>очков сезона</span></div><div class="stat"><strong>${row.wins}–${row.losses}</strong><span>победы / поражения</span></div><div class="stat"><strong>${percent(row.wins,row.games)}</strong><span>побед</span></div></div><p class="small muted">Турниров: ${row.tournaments} · Титулов: ${row.titles}. Только сохранённая история.</p><h2 class="gap">Личные встречи</h2><label class="gap">Соперник<select id="opponent" data-player="${id}"><option value="">Выберите игрока</option>${db.players.filter(x=>x.id!==id).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label><div id="duel"></div><h2 class="gap">Достижения</h2>${ach.map(a=>`<div class="achievement"><b>${esc(a.title)}</b><small>${esc(a.detail)} · ${shortDate(a.date)}</small></div>`).join('')||'<p class="muted small gap">Достижения появятся после завершённых турниров.</p>'}<h2 class="gap">Турниры</h2>${[...tournaments].reverse().map(t=>{const r=standings(t).find(x=>x.id===id);return `<a class="list-link list-item" href="#results/${t.id}"><b>${esc(t.title)}</b><br><span class="small muted">${r.place} место · ${r.points} очков турнира · +${r.seasonPoints} в сезон</span></a>`}).join('')}</section>`;}
function resultPage(id){const t=db.tournaments.find(x=>x.id===id&&x.status==='completed');if(!t)return '<section class="panel"><h2>Турнир не найден</h2><a href="#history">К истории</a></section>';const rs=standings(t),champ=rs[0],ts=completed(db),prior=ts.slice(0,ts.findIndex(x=>x.id===id)),as=awards(t,prior);return `<section class="panel winner"><span class="eyebrow" style="color:#c1d3bd">ТУРНИР ЗАВЕРШЁН · ${shortDate(t.startedAt)}</span><h1>${nm(t,champ.id)} — чемпион</h1><p class="muted">${esc(t.title)} · ${t.matches.length} матчей</p><div class="row wrap gap"><span>${champ.points} очков турнира · ${champ.wins} побед</span><span class="badge">+${champ.seasonPoints} в сезон</span></div></section><div class="desktop-columns"><section class="panel"><div class="row"><h2>Итоговые места</h2><span class="muted small">Очки / +сезон</span></div>${standingsTable(t,true)}<p class="small muted gap">При равенстве очков: % побед, средняя разница игровых очков, затем жеребьёвка.</p><div class="stack gap">${btn('Скопировать для ChatGPT','copy-report',`data-id="${t.id}"`,'primary wide')}${btn('Скачать отчёт Markdown','download-report',`data-id="${t.id}"`)}${btn('Скачать копию всей лиги','backup')}</div></section><section class="panel"><h2>Достижения вечера</h2>${as.map(a=>`<div class="achievement"><b>${nm(t,a.id)} · ${esc(a.title)}</b><small>${esc(a.detail)}</small></div>`).join('')}<details><summary>Все матчи и счета</summary>${matchList(t)}</details><details><summary>Личные встречи дня</summary>${duelsToday(t)}</details><details><summary>Обзор турнира</summary><p>${nm(t,champ.id)} набрал ${champ.points} очков и выиграл ${champ.wins} из ${champ.games} матчей. ${rs.length>1?`${nm(t,rs[1].id)} занял второе место с ${rs[1].points} очками.`:''} Все результаты сохранены.</p></details><div class="row wrap gap"><a class="btn list-link" href="#tournament">Новый турнир</a>${btn('Удалить турнир','delete',`data-id="${t.id}"`,'danger')}</div></section></div>`;}
function duelsToday(t){let s='';for(let i=0;i<t.ids.length;i++)for(let j=i+1;j<t.ids.length;j++){const h=h2h(db,t.ids[i],t.ids[j],[t]);if(h.matches.length)s+=`<p>${nm(t,t.ids[i])} — ${nm(t,t.ids[j])}: <b>${h.aWins}:${h.bWins}</b></p>`;}return s;}
function render(){if(!db)return;const route=location.hash.slice(1)||'tournament',parts=route.split('/');document.querySelectorAll('.navigation a').forEach(a=>a.classList.toggle('active',a.hash===`#${parts[0]==='results'?'history':parts[0]==='player'?'players':parts[0]}`));root.innerHTML=`<div class="rolebar"><span class="badge">${isOrganizer()?'Организатор':'Зритель'}</span><span class="small muted" id="cloud-status">${stale?'Есть новые результаты':'Общая лига · онлайн'}</span>${btn('Обновить','refresh','','text')}${btn('Сменить роль','role','','text')}</div>`+(parts[0]==='players'?playersPage():parts[0]==='history'?historyPage():parts[0]==='league'?leaguePage():parts[0]==='player'?playerPage(parts[1]):parts[0]==='results'?resultPage(parts[1]):!active()&&!isOrganizer()?'<section class="panel"><span class="eyebrow">TT LEAGUE</span><h1>Ждём следующую игру</h1><p class="muted">Сейчас нет активного турнира. Когда организатор начнёт встречу, здесь появятся текущая пара и группы.</p><div class="row wrap gap"><a class="btn" href="#history">История</a><a class="btn" href="#league">Рейтинг лиги</a></div></section>':tournamentPage());applyRole();updateClock();setTimeout(showBalanced,0);}

function showBalanced(){
  const t=active(),plan=t&&balanceProgress(t);
  if(!roleChosen||!isOrganizer()||dialog.open||!plan||plan.remaining!==0||t.current)return;
  dialog.innerHTML=`<h2>Игры выровнены</h2><p>У всех по ${plan.target} матчей. Завершить турнир или играть дальше?</p><div class="stack gap">${btn('Завершить турнир','finish',`data-id="${t.id}"`,'primary')}${btn('Продолжить турнир','continue',`data-id="${t.id}"`)}</div>`;
  dialog.oncancel=e=>e.preventDefault();dialog.onclose=null;dialog.showModal();
}

const writeActions=new Set(['balance','continue','finish','undo','delete','rename','archive','import','migrate-local']);
function applyRole(){if(isOrganizer())return;root.querySelectorAll('[data-action]').forEach(el=>{if(writeActions.has(el.dataset.action))el.remove();});root.querySelectorAll('form[data-form="start"],form[data-form="add-player"]').forEach(el=>el.remove());const score=root.querySelector('[data-form="score"]');if(score){score.querySelectorAll('input').forEach(el=>{el.disabled=true;el.placeholder='—';});score.querySelector('button').remove();score.insertAdjacentHTML('beforeend','<p class="small muted">Ждём счёт от организатора</p>');}}
function chooseRole(){return new Promise(resolve=>{dialog.innerHTML=`<h2>Добро пожаловать в TT League</h2><p class="muted small">Как вы хотите войти?</p><div class="stack gap"><button id="enter-viewer" class="btn">Войти как зритель</button><button id="enter-organizer" class="btn primary">Войти как организатор</button></div><form id="role-login" class="gap" hidden><label>Общий пароль организаторов<input name="password" type="password" autocomplete="current-password" required maxlength="72"></label><button class="btn primary wide gap">Войти</button><p id="login-error" class="notice error gap" role="alert" hidden></p></form>`;dialog.oncancel=e=>e.preventDefault();dialog.onclose=null;
  const done=()=>{roleChosen=true;dialog.oncancel=null;dialog.close();render();resolve();};
  dialog.querySelector('#enter-viewer').onclick=async()=>{await logoutOrganizer();done();};
  dialog.querySelector('#enter-organizer').onclick=()=>{dialog.querySelector('#role-login').hidden=false;dialog.querySelector('input').focus();};
  dialog.querySelector('#role-login').onsubmit=async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button'),err=form.querySelector('#login-error');button.disabled=true;dialog.querySelector('#enter-viewer').disabled=true;dialog.querySelector('#enter-organizer').disabled=true;err.hidden=true;try{await loginOrganizer(form.elements.password.value);form.reset();done();}catch(ex){err.textContent=ex.message;err.hidden=false;}finally{button.disabled=false;dialog.querySelector('#enter-viewer').disabled=false;dialog.querySelector('#enter-organizer').disabled=false;}};
  dialog.showModal();});}
function hasDraft(){return !!root.querySelector('input:focus,textarea:focus')||[...root.querySelectorAll('[data-form="score"] input')].some(el=>el.value!=='');}
async function syncCloud(force=false){if(busy||refreshing||(!force&&(dialog.open||document.hidden)))return;refreshing=true;try{const next=await readCloud();if(!db||next.revision!==db.revision){if(!force&&hasDraft()){stale=true;const status=document.querySelector('#cloud-status');if(status)status.textContent='Есть изменения · нажмите Обновить';return;}db=next;stale=false;message='';render();}else if(force){stale=false;render();}document.querySelector('#save-status').textContent='Общая база · синхронизировано';}catch(err){document.querySelector('#save-status').textContent='Нет связи с общей базой';if(force)throw err;}finally{refreshing=false;}}
function updateClock(){const el=document.querySelector('#elapsed');if(el){const min=Math.max(0,Math.floor((Date.now()-Date.parse(el.dataset.time))/60000));el.textContent=`${Math.floor(min/60)} ч ${min%60} мин · ориентир 2 ч`;}}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function downloadBackup(data=db){download(JSON.stringify(data,null,2),`tt-league-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json');}
async function copyReport(t){const text=report(db,t);try{await navigator.clipboard.writeText(text);toast('Отчёт скопирован. Вставьте его в ChatGPT.');}catch{dialog.innerHTML='<h2>Скопировать для ChatGPT</h2><p class="small muted">Выделите текст и скопируйте его вручную.</p><textarea aria-label="Отчёт турнира" readonly></textarea><div class="actions"><button class="btn primary" id="close-copy">Готово</button></div>';dialog.querySelector('textarea').value=text;dialog.querySelector('#close-copy').onclick=()=>dialog.close();dialog.showModal();dialog.querySelector('textarea').select();}}

document.addEventListener('submit',async e=>{const f=e.target;if(!f.matches('[data-form]'))return;e.preventDefault();if(busy)return;const data=new FormData(f);try{if(!isOrganizer())throw Error('Войдите как организатор.');
  if(f.dataset.form==='add-player'){const ids=await mutate(next=>addPlayers(next,String(data.get('names'))));ids.forEach(id=>selected.add(id));render();toast('Профили сохранены');}
  if(f.dataset.form==='start'){const ids=data.getAll('participant'),title=String(data.get('title')||`TT League · ${shortDate(new Date())}`);await mutate(next=>createTournament(next,ids,title));message='';draftTitle='';render();toast('Турнир начался. Первая пара уже у стола.');}
  if(f.dataset.form==='score'){const a=Number(data.get('a')),b=Number(data.get('b'));const result=await mutate(next=>{const t=next.tournaments.find(x=>x.id===f.dataset.tournament);if(!t||t.revision!==Number(f.dataset.revision)||t.matches.length!==Number(f.dataset.matchCount))throw Error('Этот результат уже сохранён.');return recordScore(t,a,b);});const t=active();message=`${t.names[result.winner]} +${result.points}. ${t.names[result.a]} → ${transition(result.levelA,result.winner===result.a)}; ${t.names[result.b]} → ${transition(result.levelB,result.winner===result.b)}.`;render();}
}catch(err){if(f.dataset.form==='score'){const el=document.querySelector('#score-error');if(el)el.textContent=err.message;}else error(err);}});
document.addEventListener('input',e=>{if(e.target.name==='title')draftTitle=e.target.value;});
document.addEventListener('change',async e=>{if(e.target.name==='participant'){e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);document.querySelector('#selected-count').textContent=`Выбрано: ${selected.size} из ${MIN_PLAYERS}–${MAX_PLAYERS}`;document.querySelector('#start-button').disabled=selected.size<MIN_PLAYERS||selected.size>MAX_PLAYERS;}
  if(e.target.id==='opponent'){const a=e.target.dataset.player,b=e.target.value,el=document.querySelector('#duel');if(!b){el.innerHTML='';return;}const h=h2h(db,a,b);el.innerHTML=`<div class="stats-duel">${h.aWins} : ${h.bWins}</div><p class="muted small">${esc(db.players.find(p=>p.id===a).name)} — ${esc(db.players.find(p=>p.id===b).name)} · ${h.matches.length} матчей</p>${[...h.matches].reverse().map(m=>`<div class="list-item small">${esc(m.tournamentTitle)} · ${shortDate(m.date)}<br>${esc(db.players.find(p=>p.id===m.a).name)} — ${esc(db.players.find(p=>p.id===m.b).name)} <b>${m.scoreA}:${m.scoreB}</b></div>`).join('')}`;}
  if(e.target.id==='import-file'&&e.target.files[0]){const file=e.target.files[0];try{if(!isOrganizer())throw Error('Войдите как организатор.');if(file.size>20000000)throw Error('Файл слишком большой (максимум 20 МБ).');const data=validateDB(JSON.parse(await file.text()));if(await ask('Восстановить лигу?',`В файле ${data.players.length} игроков и ${data.tournaments.length} турниров. Общая база будет заменена для всех устройств. Сначала скачаем вашу текущую копию; она также останется в резерве на устройстве.`,'Восстановить')){downloadBackup();await backupBeforeReplace(db);await mutate(next=>{Object.assign(next,data);});selected.clear();message='';navigate('#history');toast('Лига восстановлена');}}catch(err){error(err);}e.target.value='';}
});
document.addEventListener('click',async e=>{const target=e.target.closest('[data-action]');if(!target||busy)return;const {action,id}=target.dataset;try{
  if(action==='role'){await logoutOrganizer();render();await chooseRole();return;}
  if(action==='refresh'){if(hasDraft()&&!await ask('Обновить данные?','Несохранённый ввод счёта будет сброшен. Загрузим текущий матч из общей базы.','Обновить'))return;await syncCloud(true);toast('Общие данные обновлены');return;}
  if(writeActions.has(action)&&!isOrganizer())throw Error('Войдите как организатор.');
  if(action==='migrate-local'){if(await ask('Перенести старую лигу?',`На этом устройстве ${legacy.players.length} игроков и ${legacy.tournaments.length} турниров. Эти данные заменят общую лигу для всех. Сначала скачаем копию нынешней общей базы.`,'Перенести')){downloadBackup();await backupBeforeReplace(db);await mutate(next=>Object.assign(next,clone(legacy)));navigate('#history');toast('История перенесена в общую базу');}return;}
  if(action==='balance'){
    const t=active(),plan=balancePlan(t),revision=t.revision;
    if(hasDraft()){toast('Сначала сохраните введённый счёт.');return;}
    if(await ask('Выровнять игры?',`Цель: по ${plan.target} матчей каждому. Осталось встреч: ${plan.remaining}. Текущая несохранённая пара будет заменена. Если матч уже сыгран, сначала внесите счёт.`,'Выровнять')){
      await mutate(next=>{const current=next.tournaments.find(x=>x.id===id);if(current.revision!==revision)throw Error('Данные изменились. Обновите страницу.');startBalance(current);});message='';render();
    }
  }
  if(action==='continue'){if(dialog.open)dialog.close();await mutate(next=>continueTournament(next.tournaments.find(x=>x.id===id)));message='Турнир продолжается. Выравнивание можно включить снова.';render();}
  if(action==='finish'){const t=active(),balanced=balanceProgress(t)?.remaining===0;if(dialog.open){dialog.onclose=null;dialog.close();}if(t.matches.length<Math.floor(t.ids.length/2)){toast('Сначала закончите стартовые матчи. Тест можно удалить в истории.');return;}if(balanced||await ask('Завершить турнир?',`Сохраним ${t.matches.length} матчей и рассчитаем места. Следующая показанная пара не будет учтена. Если вы уже сыграли её, сначала внесите счёт.`,'Завершить')){await mutate(next=>finish(next.tournaments.find(x=>x.id===id)));message='';navigate(`#results/${id}`);toast('Турнир сохранён в истории');}}
  if(action==='undo'&&await ask('Отменить последний счёт?','Последний результат и его очки будут отменены. Эта же пара снова получит поля для ввода счёта.','Отменить результат')){await mutate(next=>undoLast(next.tournaments.find(x=>x.id===id)));message='Последний результат отменён. Введите правильный счёт.';render();}
  if(action==='delete'){const t=db.tournaments.find(x=>x.id===id);if(await ask('Удалить турнир?',`«${esc(t.title)}» и его ${t.matches.length} матчей будут удалены. Рейтинг, личные встречи и ачивки пересчитаются без этого турнира. Профили останутся. Это действие нельзя отменить без резервной копии.`,'Удалить турнир',true)){await mutate(next=>removeTournament(next,id));message='';navigate('#history');toast('Турнир удалён. Статистика пересчитана.');}}
  if(action==='rename'){const p=db.players.find(x=>x.id===id),name=await ask('Имя игрока','История останется привязана к этому профилю. В старых турнирах сохранится имя на момент игры.','Сохранить',false,p.name);if(name){await mutate(next=>{if(next.players.some(x=>x.id!==id&&x.name.toLowerCase()===name.toLowerCase()))throw Error('Такое имя уже есть. Добавьте фамилию или инициал.');next.players.find(x=>x.id===id).name=name;});}}
  if(action==='archive'){await mutate(next=>{if(next.tournaments.some(t=>t.status==='active'&&t.ids.includes(id)))throw Error('Игрок участвует в текущем турнире. Сначала завершите его.');const p=next.players.find(x=>x.id===id);p.archived=!p.archived;});}
  if(action==='copy-report')await copyReport(db.tournaments.find(t=>t.id===id));
  if(action==='download-report')download(report(db,db.tournaments.find(t=>t.id===id)),`tt-league-${id}.md`,'text/markdown;charset=utf-8');
  if(action==='backup'){downloadBackup();toast('Резервная копия подготовлена');}
  if(action==='import')document.querySelector('#import-file').click();
  if(action==='previous-backup'){const previous=await readPreviousBackup();if(previous)downloadBackup(previous);else toast('Резерв перед импортом пока не создавался.');}
}catch(err){error(err);}});
window.addEventListener('hashchange',()=>{message='';render();window.scrollTo(0,0);});setInterval(updateClock,15000);
async function boot(){
  try {
    try {legacy=await openStore();}catch {legacy=null;}
    db=await readCloud();render();
    if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
    await chooseRole();
    setInterval(()=>syncCloud(),5000);
    document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncCloud();});
  }catch(err){root.innerHTML=`<section class="panel"><h1>Подключаем общую лигу</h1><p>${esc(err.message)}</p><p class="muted small gap">Старые данные этого браузера сохранены. После настройки базы они доступны для переноса организатором.</p><div class="row gap"><button class="btn primary" onclick="location.reload()">Проверить снова</button>${legacy?btn('Скачать старые данные','download-legacy'):''}</div></section>`;}
}
document.addEventListener('click',e=>{if(e.target.closest('[data-action="download-legacy"]')&&legacy)downloadBackup(legacy);});
boot();
